### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by sonasapps** [HuangRunHua/LiveTextWithImage#1]
Thanks for this guide! I have images in CoreData that are stored as data

`var image1: Data = .init(count: 0)`

Then when I display the saved images, they look like

`Image(uiImage: UIImage(data: self.image1))`

How would I update your `LiveTextInteraction.swift` to support this setup, since your example is using `UIImage(named: <string>)`

Thanks!

**Comment by HuangRunHua** [comment]
Hi there, you can simply change the type of `imageName` to data in the `LiveTextInteraction.swift`:
```swift

struct LiveTextInteraction: UIViewRepresentable {
    var imageName: String
    ...
}
```

Then you can use Core Data in your project.

**Comment by HuangRunHua** [comment]
> Thanks for this guide! I have images in CoreData that are stored as data
> 
> 
> 
> `var image1: Data = .init(count: 0)`
> 
> 
> 
> Then when I display the saved images, they look like
> 
> 
> 
> `Image(uiImage: UIImage(data: self.image1))`
> 
> 
> 
> How would I update your `LiveTextInteraction.swift` to support this setup, since your example is using `UIImage(named: <string>)`
> 
> 
> 
> Thanks!

Hi there, you can simply change the type of `imageName` to `data` in the `LiveTextInteraction.swift`:
```swift

struct LiveTextInteraction: UIViewRepresentable {
    var imageName: Data
    ...
}
```

Then you can use Core Data in your project.
